### ISSUE TITLE
use grafana dataset as data in vega

### ISSUE THREAD

**Issue by exile79** [schicks/vega-grafana#1]
Hello

I would like to visualize some data from a dataset using the vega grammar.
If I copy-paste a vega example, the plugin works as expected with the hard-coded data
Is it possible to use grafana data provided by a query? Is this supported in any way?
Thanx

**Comment by schicks** [comment]
I've not been working actively on this repo. Until I have a workaround for [this issue](https://community.grafana.com/t/ace-dependency-conflicts/35502), I'm not really sure how to get it to a completed state. That being said, if you leave off the `data` property from your spec the plugin should provide a [data property](https://github.com/schicks/vega-grafana/blob/2e70f4d020d244a8d56c526d984b07f01f678531/src/SimplePanel.tsx#L54) populated with data from grafana. Does that answer your question?

**Comment by exile79** [comment]
Yes, thank you
